/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeBody.java */

package softtest.ast.java;

public class ASTAnnotationTypeBody extends SimpleJavaNode {
    public ASTAnnotationTypeBody(int id) {
        super(id);
    }

    public ASTAnnotationTypeBody(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
