/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeMemberDeclaration.java */

package softtest.ast.java;

public class ASTAnnotationTypeMemberDeclaration extends SimpleJavaNode {
    public ASTAnnotationTypeMemberDeclaration(int id) {
        super(id);
    }

    public ASTAnnotationTypeMemberDeclaration(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
