/* Generated By:JJTree: Do not edit this line. ASTArguments.java */

package softtest.ast.java;

public class ASTArguments extends ExpressionBase {
    public ASTArguments(int id) {
        super(id);
    }

    public ASTArguments(JavaParser p, int id) {
        super(p, id);
    }

    public Class[] getParameterTypes() {
    	if (this.getArgumentCount() > 0) {
    		return ((ASTArgumentList)jjtGetChild(0)).getParameterTypes();
    	} else {
    		return null;
    	}
	}

    public int getArgumentCount() {
        if (this.jjtGetNumChildren() == 0) {
            return 0;
        }
        return this.jjtGetChild(0).jjtGetNumChildren();
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
