/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java */

package softtest.ast.java;

public class ASTAssertStatement extends SimpleJavaNode {
    public ASTAssertStatement(int id) {
        super(id);
    }

    public ASTAssertStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
