/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeDeclaration.java */

package softtest.ast.java;

public class ASTAnnotationTypeDeclaration extends AccessNode {
    public ASTAnnotationTypeDeclaration(int id) {
        super(id);
    }

    public ASTAnnotationTypeDeclaration(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
