/* Generated By:JJTree: Do not edit this line. ASTAdditiveExpression.java */

package softtest.ast.java;

public class ASTAdditiveExpression extends ExpressionBase {
    public ASTAdditiveExpression(int id) {
        super(id);
    }

    public ASTAdditiveExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
