/* Generated By:JJTree: Do not edit this line. ASTAllocationExpression.java */

package softtest.ast.java;

public class ASTAllocationExpression extends ExpressionBase {
    public ASTAllocationExpression(int id) {
        super(id);
    }

    public ASTAllocationExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    //added by xqing
       
    private int anonymous_num=0;
    
    public void setAnonymousNum(int num){
    	anonymous_num=num;
    }
      
    public int getAnonymousNum(){
    	return anonymous_num;
    }
}
