/* Generated By:JJTree: Do not edit this line. ASTConstructorBlock.java */

package softtest.ast.java;

public class ASTConstructorBlock extends SimpleJavaNode {
  public ASTConstructorBlock(int id) {
    super(id);
  }

  public ASTConstructorBlock(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
