/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBodyDeclaration.java */

package softtest.ast.java;

public class ASTClassOrInterfaceBodyDeclaration extends SimpleJavaNode {

    public ASTClassOrInterfaceBodyDeclaration(int id) {
        super(id);
    }

    public ASTClassOrInterfaceBodyDeclaration(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public boolean isAnonymousInnerClass() {
        return jjtGetParent().jjtGetParent() instanceof ASTAllocationExpression;
    }

    public boolean isEnumChild() {
        return jjtGetParent().jjtGetParent() instanceof ASTEnumConstant;
    }

    @Override
	public void dump(String prefix) {
        String isAnonyString = isAnonymousInnerClass() ? ": (anonymous inner class)" : "";
        System.out.println(toString(prefix) + isAnonyString);
        dumpChildren(prefix);
    }

}
