/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExpression.java */

package softtest.ast.java;

public class ASTConditionalAndExpression extends ExpressionBase {
    public ASTConditionalAndExpression(int id) {
        super(id);
    }

    public ASTConditionalAndExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
