/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java */

package softtest.ast.java;

public class ASTDoStatement extends SimpleJavaNode {
    public ASTDoStatement(int id) {
        super(id);
    }

    public ASTDoStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
