/* Generated By:JJTree: Do not edit this line. ASTEqualityExpression.java */

package softtest.ast.java;

public class ASTEqualityExpression extends ExpressionBase {
    public ASTEqualityExpression(int id) {
        super(id);
    }

    public ASTEqualityExpression(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
