/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java */

package softtest.ast.java;

public class ASTExclusiveOrExpression extends ExpressionBase {
    public ASTExclusiveOrExpression(int id) {
        super(id);
    }

    public ASTExclusiveOrExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
