/* Generated By:JJTree: Do not edit this line. ASTEnumDeclaration.java */

package softtest.ast.java;

public class ASTEnumDeclaration extends AccessNode {
    public ASTEnumDeclaration(int id) {
        super(id);
    }

    public ASTEnumDeclaration(JavaParser p, int id) {
        super(p, id);
    }

    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
