/* Generated By:JJTree: Do not edit this line. ASTEnumBody.java */

package softtest.ast.java;

public class ASTEnumBody extends SimpleJavaNode {
    public ASTEnumBody(int id) {
        super(id);
    }

    public ASTEnumBody(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
