/* Generated By:JJTree: Do not edit this line. ASTEnumElement.java */

package softtest.ast.java;

public class ASTEnumElement extends SimpleJavaNode {
    public ASTEnumElement(int id) {
        super(id);
    }

    public ASTEnumElement(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
