/* Generated By:JJTree: Do not edit this line. ASTExtendsList.java */

package softtest.ast.java;

public class ASTExtendsList extends SimpleJavaNode {
    public ASTExtendsList(int id) {
        super(id);
    }

    public ASTExtendsList(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
