/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java */

package softtest.ast.java;

public class ASTEmptyStatement extends SimpleJavaNode {
    public ASTEmptyStatement(int id) {
        super(id);
    }

    public ASTEmptyStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
