/* Generated By:JJTree: Do not edit this line. ASTEnumConstant.java */

package softtest.ast.java;

public class ASTEnumConstant extends SimpleJavaNode {
    public ASTEnumConstant(int id) {
        super(id);
    }

    public ASTEnumConstant(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    @Override
	public void dump(String prefix) {
        System.out.println(toString(prefix) + getImage());
        dumpChildren(prefix);
    }
}
