/* Generated By:JJTree: Do not edit this line. ASTForInit.java */

package softtest.ast.java;

public class ASTForInit extends SimpleJavaNode {
    public ASTForInit(int id) {
        super(id);
    }

    public ASTForInit(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
