/* Generated By:JJTree: Do not edit this line. ASTForEachVariableDeclaration.java */

package softtest.ast.java;

public class ASTForEachVariableDeclaration extends AccessNode {
  public ASTForEachVariableDeclaration(int id) {
    super(id);
  }

  public ASTForEachVariableDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
