/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java */

package softtest.ast.java;

import softtest.symboltable.java.TypeSet;

public class ASTFormalParameters extends SimpleJavaNode {
    public ASTFormalParameters(int id) {
        super(id);
    }

    public ASTFormalParameters(JavaParser p, int id) {
        super(p, id);
    }

    public int getParameterCount() {
        return jjtGetNumChildren();
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    // add by yangxiu
	public Class[] getParameterTypes() {
		Class[] ret=new Class[jjtGetNumChildren()];
		for (int i=0;i<jjtGetNumChildren();++i) {
			ASTFormalParameter fp = (ASTFormalParameter) jjtGetChild(i);
			ret[i]=TypeSet.getCurrentTypeSet().findClassWithoutEx(fp.getTypeNode().getTypeImage());
		}
		return ret;
	}
}
