/* Generated By:JJTree: Do not edit this line. ASTInclusiveOrExpression.java */

package softtest.ast.java;

public class ASTInclusiveOrExpression extends ExpressionBase {
    public ASTInclusiveOrExpression(int id) {
        super(id);
    }

    public ASTInclusiveOrExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
