/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java */

package softtest.ast.java;

public class ASTInstanceOfExpression extends ExpressionBase {
    public ASTInstanceOfExpression(int id) {
        super(id);
    }

    public ASTInstanceOfExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
