/* Generated By:JJTree: Do not edit this line. ASTLabeledStatement.java */

package softtest.ast.java;

public class ASTLabeledStatement extends SimpleJavaNode {
    public ASTLabeledStatement(int id) {
        super(id);
    }

    public ASTLabeledStatement(JavaParser p, int id) {
        super(p, id);
    }

    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
