/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

package softtest.ast.java;

public class ASTLiteral extends ExpressionBase {
    public ASTLiteral(int id) {
        super(id);
    }

    public ASTLiteral(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public boolean isStringLiteral() {
        return getImage() != null && getImage().startsWith("\"") && getImage().endsWith("\"");
    }
}
