/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java */

package softtest.ast.java;
//added by xqing
import softtest.symboltable.java.MethodNameDeclaration;


public class ASTMethodDeclarator extends SimpleJavaNode {
    public ASTMethodDeclarator(int id) {
        super(id);
    }

    public ASTMethodDeclarator(JavaParser p, int id) {
        super(p, id);
    }

    public int getParameterCount() {
        return this.jjtGetChild(0).jjtGetNumChildren();
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    //added by xqing
    MethodNameDeclaration mnd =null;
    
    public void setMethodNameDeclaration(MethodNameDeclaration mnd){
    	this.mnd=mnd;
    }
    
    public MethodNameDeclaration getMethodNameDeclaration(){
    	return this.mnd;
    }

    //added by yangxiu
	public Class[] getParameterTypes() {		
		return ((ASTFormalParameters)this.jjtGetChild(0)).getParameterTypes();
	}
}
