/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java */

package softtest.ast.java;

public class ASTMemberValueArrayInitializer extends SimpleJavaNode {
    public ASTMemberValueArrayInitializer(int id) {
        super(id);
    }

    public ASTMemberValueArrayInitializer(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
