/* Generated By:JJTree: Do not edit this line. ASTMemberValuePairs.java */

package softtest.ast.java;

public class ASTMemberValuePairs extends SimpleJavaNode {
    public ASTMemberValuePairs(int id) {
        super(id);
    }

    public ASTMemberValuePairs(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
