/* Generated By:JJTree: Do not edit this line. ASTNameList.java */

package softtest.ast.java;

public class ASTNameList extends SimpleJavaNode {
    public ASTNameList(int id) {
        super(id);
    }

    public ASTNameList(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
