/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package softtest.ast.java;

public class ASTNullLiteral extends ExpressionBase {
    public ASTNullLiteral(int id) {
        super(id);
    }

    public ASTNullLiteral(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
