/* Generated By:JJTree: Do not edit this line. ASTPostfixExpression.java */

package softtest.ast.java;

public class ASTPostfixExpression extends ExpressionBase {

    public ASTPostfixExpression(int id) {
        super(id);
    }

    public ASTPostfixExpression(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
