/* Generated By:JJTree: Do not edit this line. ASTPreIncrementExpression.java */

package softtest.ast.java;

public class ASTPreIncrementExpression extends ExpressionBase {
    public ASTPreIncrementExpression(int id) {
        super(id);
    }

    public ASTPreIncrementExpression(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
