/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java */

package softtest.ast.java;


import softtest.symboltable.java.NameDeclaration;

public class ASTPrimarySuffix extends ExpressionBase {
    public ASTPrimarySuffix(int id) {
        super(id);
    }

    public ASTPrimarySuffix(JavaParser p, int id) {
        super(p, id);
    }

    private boolean isArguments;
    private boolean isArrayDereference;
    private boolean usesThisModifier;
    private boolean usesSuperModifier;

    public void setUsesThisModifier() {
        usesThisModifier = true;
    }

    public boolean usesThisModifier() {
        return this.usesThisModifier;
    }

    public void setUsesSuperModifier() {
        usesSuperModifier = true;
    }

    public boolean usesSuperModifier() {
        return this.usesSuperModifier;
    }    

    public void setIsArrayDereference() {
        isArrayDereference = true;
    }

    public boolean isArrayDereference() {
        return isArrayDereference;
    }

    public void setIsArguments() {
        this.isArguments = true;
    }

    public boolean isArguments() {
        return this.isArguments;
    }

    public int getArgumentCount() {
        if (!this.isArguments()) {
            throw new RuntimeException("ASTPrimarySuffix.getArgumentCount called, but this is not a method call");
        }
        return ((ASTArguments)this.getFirstChildOfType(ASTArguments.class)).getArgumentCount();
    }

    @Override
	public void dump(String prefix) {
        String out = "";
        if (isArrayDereference()) {
            out += ":[";
        }
        if (this.getImage() != null) {
            out += out.length() == 0 ? ":" + this.getImage() : this.getImage();
        }
        System.out.println(toString(prefix) + out);
        dumpChildren(prefix);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    //added by xqing
    private NameDeclaration nd;
 
    public void setNameDeclaration(NameDeclaration nd) {
        this.nd = nd;
    }

    public NameDeclaration getNameDeclaration() {
    	return this.nd;
    }
    
	public boolean isMethodName() {
		boolean ret = false;
		if (jjtGetParent() instanceof ASTPrimaryExpression) {
			ASTPrimaryExpression primaryexpr = (ASTPrimaryExpression) jjtGetParent();
			int find = -1;
			for (int i = 0; i < primaryexpr.jjtGetNumChildren(); i++) {
				if (primaryexpr.jjtGetChild(i) == this) {
					find = i;
					break;
				}
			}
			if (find >= 0 && primaryexpr.jjtGetNumChildren() > find + 1) {
				if (primaryexpr.jjtGetChild(find + 1) instanceof ASTPrimarySuffix) {
					ASTPrimarySuffix suffix = (ASTPrimarySuffix) primaryexpr
							.jjtGetChild(find + 1);
					if (suffix.isArguments()) {
						ret = true;
					}
				}
			}
		}
		return ret;
	}
		
    public Class[] getParameterTypes() {
		Class[] types = null;

		if (jjtGetParent() instanceof ASTPrimaryExpression) {
			ASTPrimaryExpression primaryexpr = (ASTPrimaryExpression) jjtGetParent();
			int find = -1;
			for (int i = 0; i < primaryexpr.jjtGetNumChildren(); i++) {
				if (primaryexpr.jjtGetChild(i) == this) {
					find = i;
					break;
				}
			}
			if (find >= 0 && primaryexpr.jjtGetNumChildren() > find + 1) {
				if (primaryexpr.jjtGetChild(find + 1) instanceof ASTPrimarySuffix) {
					ASTPrimarySuffix suffix = (ASTPrimarySuffix) primaryexpr
							.jjtGetChild(find + 1);
					if (suffix.isArguments()) {
						ASTArguments args = (ASTArguments) suffix
								.jjtGetChild(0);
						if (args.jjtGetNumChildren() > 0) {
							ASTArgumentList argslist = (ASTArgumentList) args
									.jjtGetChild(0);
							types = new Class[argslist.jjtGetNumChildren()];
							for (int i = 0; i < argslist.jjtGetNumChildren(); i++) {
								ExpressionBase e = (ExpressionBase) argslist
										.jjtGetChild(i);
								try {
									types[i] = (Class) e.getType();
								} catch (ClassCastException ex) {
									// TODO : BUGFIX
									// fields from super class
									//throw new RuntimeException(this.getBeginLine()+":"+this.getBeginColumn(),e);
								}
							}
						}
					}
				}
			}
		}
		return types;
	}
	public ExpressionBase getLastExpression(){
		ExpressionBase e=null;
		if (jjtGetParent() instanceof ASTPrimaryExpression) {
			ASTPrimaryExpression primaryexpr = (ASTPrimaryExpression) jjtGetParent();
			int find = -1;
			for (int i = 0; i < primaryexpr.jjtGetNumChildren(); i++) {
				if (primaryexpr.jjtGetChild(i) == this) {
					find = i;
					break;
				}
			}
			if (find >= 0 ) {
				if (primaryexpr.jjtGetChild(find - 1) instanceof ExpressionBase) {
					e=(ExpressionBase)primaryexpr.jjtGetChild(find - 1);
				}
			}
		}
		return e;
	}
}
