/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

package softtest.ast.java;

public class ASTReturnStatement extends SimpleJavaNode {
    public ASTReturnStatement(int id) {
        super(id);
    }

    public ASTReturnStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
