/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java */

package softtest.ast.java;

public class ASTRUNSIGNEDSHIFT extends SimpleJavaNode {
    public ASTRUNSIGNEDSHIFT(int id) {
        super(id);
    }

    public ASTRUNSIGNEDSHIFT(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
