/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java */

package softtest.ast.java;

public class ASTSingleMemberAnnotation extends SimpleJavaNode {
    public ASTSingleMemberAnnotation(int id) {
        super(id);
    }

    public ASTSingleMemberAnnotation(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
