/* Generated By:JJTree: Do not edit this line. ASTSynchronizedStatement.java */

package softtest.ast.java;

public class ASTSynchronizedStatement extends SimpleJavaNode {
    public ASTSynchronizedStatement(int id) {
        super(id);
    }

    public ASTSynchronizedStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
