/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java */

package softtest.ast.java;

public class ASTSwitchStatement extends SimpleJavaNode {
    public ASTSwitchStatement(int id) {
        super(id);
    }

    public ASTSwitchStatement(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
