/* Generated By:JJTree: Do not edit this line. ASTShiftExpression.java */

package softtest.ast.java;

public class ASTShiftExpression extends ExpressionBase {
    public ASTShiftExpression(int id) {
        super(id);
    }

    public ASTShiftExpression(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
