/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java */

package softtest.ast.java;

public class ASTUnaryExpression extends ExpressionBase {
    public ASTUnaryExpression(int id) {
        super(id);
    }

    public ASTUnaryExpression(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
