/* Generated By:JJTree: Do not edit this line. ASTUnaryExpressionNotPlusMinus.java */

package softtest.ast.java;

public class ASTUnaryExpressionNotPlusMinus extends ExpressionBase {
    public ASTUnaryExpressionNotPlusMinus(int id) {
        super(id);
    }

    public ASTUnaryExpressionNotPlusMinus(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
