/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java */

package softtest.ast.java;

public class ASTVariableDeclarator extends SimpleJavaNode {
    public ASTVariableDeclarator(int id) {
        super(id);
    }

    public ASTVariableDeclarator(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
