/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java */

package softtest.ast.java;

public class ASTWildcardBounds extends SimpleJavaNode {
    public ASTWildcardBounds(int id) {
        super(id);
    }

    public ASTWildcardBounds(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    @Override
	public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
