/* Generated By:JJTree: Do not edit this line. .\JavaParserTreeConstants.java */

package softtest.ast.java;

public interface JavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTVOID = 3;
  public int JJTTYPEDECLARATION = 4;
  public int JJTCLASSORINTERFACEDECLARATION = 5;
  public int JJTEXTENDSLIST = 6;
  public int JJTIMPLEMENTSLIST = 7;
  public int JJTENUMDECLARATION = 8;
  public int JJTENUMBODY = 9;
  public int JJTENUMCONSTANT = 10;
  public int JJTTYPEPARAMETERS = 11;
  public int JJTTYPEPARAMETER = 12;
  public int JJTTYPEBOUND = 13;
  public int JJTCLASSORINTERFACEBODY = 14;
  public int JJTCLASSORINTERFACEBODYDECLARATION = 15;
  public int JJTFIELDDECLARATION = 16;
  public int JJTVARIABLEDECLARATOR = 17;
  public int JJTVARIABLEDECLARATORID = 18;
  public int JJTVARIABLEINITIALIZER = 19;
  public int JJTARRAYINITIALIZER = 20;
  public int JJTMETHODDECLARATION = 21;
  public int JJTMETHODDECLARATOR = 22;
  public int JJTFORMALPARAMETERS = 23;
  public int JJTFORMALPARAMETER = 24;
  public int JJTCONSTRUCTORDECLARATION = 25;
  public int JJTCONSTRUCTORBLOCK = 26;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 27;
  public int JJTINITIALIZER = 28;
  public int JJTTYPE = 29;
  public int JJTREFERENCETYPE = 30;
  public int JJTCLASSORINTERFACETYPE = 31;
  public int JJTTYPEARGUMENTS = 32;
  public int JJTTYPEARGUMENT = 33;
  public int JJTWILDCARDBOUNDS = 34;
  public int JJTPRIMITIVETYPE = 35;
  public int JJTRESULTTYPE = 36;
  public int JJTNAME = 37;
  public int JJTNAMELIST = 38;
  public int JJTEXPRESSION = 39;
  public int JJTASSIGNMENTOPERATOR = 40;
  public int JJTCONDITIONALEXPRESSION = 41;
  public int JJTCONDITIONALOREXPRESSION = 42;
  public int JJTCONDITIONALANDEXPRESSION = 43;
  public int JJTINCLUSIVEOREXPRESSION = 44;
  public int JJTEXCLUSIVEOREXPRESSION = 45;
  public int JJTANDEXPRESSION = 46;
  public int JJTEQUALITYEXPRESSION = 47;
  public int JJTINSTANCEOFEXPRESSION = 48;
  public int JJTRELATIONALEXPRESSION = 49;
  public int JJTSHIFTEXPRESSION = 50;
  public int JJTADDITIVEEXPRESSION = 51;
  public int JJTMULTIPLICATIVEEXPRESSION = 52;
  public int JJTUNARYEXPRESSION = 53;
  public int JJTPREINCREMENTEXPRESSION = 54;
  public int JJTPREDECREMENTEXPRESSION = 55;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 56;
  public int JJTPOSTFIXEXPRESSION = 57;
  public int JJTCASTEXPRESSION = 58;
  public int JJTPRIMARYEXPRESSION = 59;
  public int JJTMEMBERSELECTOR = 60;
  public int JJTPRIMARYPREFIX = 61;
  public int JJTPRIMARYSUFFIX = 62;
  public int JJTLITERAL = 63;
  public int JJTBOOLEANLITERAL = 64;
  public int JJTNULLLITERAL = 65;
  public int JJTARGUMENTS = 66;
  public int JJTARGUMENTLIST = 67;
  public int JJTALLOCATIONEXPRESSION = 68;
  public int JJTARRAYDIMSANDINITS = 69;
  public int JJTSTATEMENT = 70;
  public int JJTLABELEDSTATEMENT = 71;
  public int JJTBLOCK = 72;
  public int JJTBLOCKSTATEMENT = 73;
  public int JJTLOCALVARIABLEDECLARATION = 74;
  public int JJTEMPTYSTATEMENT = 75;
  public int JJTSTATEMENTEXPRESSION = 76;
  public int JJTSWITCHSTATEMENT = 77;
  public int JJTSWITCHLABEL = 78;
  public int JJTIFSTATEMENT = 79;
  public int JJTWHILESTATEMENT = 80;
  public int JJTDOSTATEMENT = 81;
  public int JJTFORSTATEMENT = 82;
  public int JJTFOREACHVARIABLEDECLARATION = 83;
  public int JJTFORINIT = 84;
  public int JJTSTATEMENTEXPRESSIONLIST = 85;
  public int JJTFORUPDATE = 86;
  public int JJTBREAKSTATEMENT = 87;
  public int JJTCONTINUESTATEMENT = 88;
  public int JJTRETURNSTATEMENT = 89;
  public int JJTTHROWSTATEMENT = 90;
  public int JJTSYNCHRONIZEDSTATEMENT = 91;
  public int JJTTRYSTATEMENT = 92;
  public int JJTCATCHSTATEMENT = 93;
  public int JJTFINALLYSTATEMENT = 94;
  public int JJTASSERTSTATEMENT = 95;
  public int JJTRUNSIGNEDSHIFT = 96;
  public int JJTRSIGNEDSHIFT = 97;
  public int JJTANNOTATION = 98;
  public int JJTNORMALANNOTATION = 99;
  public int JJTMARKERANNOTATION = 100;
  public int JJTSINGLEMEMBERANNOTATION = 101;
  public int JJTMEMBERVALUEPAIRS = 102;
  public int JJTMEMBERVALUEPAIR = 103;
  public int JJTMEMBERVALUE = 104;
  public int JJTMEMBERVALUEARRAYINITIALIZER = 105;
  public int JJTANNOTATIONTYPEDECLARATION = 106;
  public int JJTANNOTATIONTYPEBODY = 107;
  public int JJTANNOTATIONTYPEMEMBERDECLARATION = 108;
  public int JJTDEFAULTVALUE = 109;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "void",
    "TypeDeclaration",
    "ClassOrInterfaceDeclaration",
    "ExtendsList",
    "ImplementsList",
    "EnumDeclaration",
    "EnumBody",
    "EnumConstant",
    "TypeParameters",
    "TypeParameter",
    "TypeBound",
    "ClassOrInterfaceBody",
    "ClassOrInterfaceBodyDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ConstructorBlock",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "WildcardBounds",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "MemberSelector",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForEachVariableDeclaration",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "CatchStatement",
    "FinallyStatement",
    "AssertStatement",
    "RUNSIGNEDSHIFT",
    "RSIGNEDSHIFT",
    "Annotation",
    "NormalAnnotation",
    "MarkerAnnotation",
    "SingleMemberAnnotation",
    "MemberValuePairs",
    "MemberValuePair",
    "MemberValue",
    "MemberValueArrayInitializer",
    "AnnotationTypeDeclaration",
    "AnnotationTypeBody",
    "AnnotationTypeMemberDeclaration",
    "DefaultValue",
  };
}
